In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Z:/codes/python/datasets/pokemon.csv")
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

In [10]:
df.groupby('Type1')["Height"].mean()

Type1
Bug         0.900000
Dragon      2.666667
Electric    0.855556
Fairy       0.950000
Fighting    1.185714
Fire        1.216667
Ghost       1.466667
Grass       1.083333
Ground      0.850000
Ice         1.550000
Normal      0.986364
Poison      1.221429
Psychic     1.371429
Rock        1.844444
Water       1.300000
Name: Height, dtype: float64

# make a new column and add it to the existing dataframe

In [12]:
df["Type1_new"] = df["Type1"].apply((lambda x:x.upper()))
df

      No        Name    Type1   Type2  Height  Weight  Legendary Type1_new
0      1   bulbasaur    Grass  Poison     0.7     6.9          0     GRASS
1      2     ivysaur    Grass  Poison     1.0    13.0          0     GRASS
2      3    venusaur    Grass  Poison     2.0   100.0          0     GRASS
3      4  charmander     Fire     NaN     0.6     8.5          0      FIRE
4      5  charmeleon     Fire     NaN     1.1    19.0          0      FIRE
..   ...         ...      ...     ...     ...     ...        ...       ...
145  146     moltres     Fire  Flying     2.0    60.0          1      FIRE
146  147     dratini   Dragon     NaN     1.8     3.3          0    DRAGON
147  148   dragonair   Dragon     NaN     4.0    16.5          0    DRAGON
148  149   dragonite   Dragon  Flying     2.2   210.0          0    DRAGON
149  150      mewtwo  Psychic     NaN     2.0   122.0          1   PSYCHIC

[150 rows x 8 columns]

In [5]:
df["Name"] = df["Name"].str.lower()
df

      No        Name    Type1   Type2  Height  Weight  Legendary Type1_new
0      1   bulbasaur    Grass  Poison     0.7     6.9          0     GRASS
1      2     ivysaur    Grass  Poison     1.0    13.0          0     GRASS
2      3    venusaur    Grass  Poison     2.0   100.0          0     GRASS
3      4  charmander     Fire     NaN     0.6     8.5          0      Fire
4      5  charmeleon     Fire     NaN     1.1    19.0          0      Fire
..   ...         ...      ...     ...     ...     ...        ...       ...
145  146     moltres     Fire  Flying     2.0    60.0          1      Fire
146  147     dratini   Dragon     NaN     1.8     3.3          0    Dragon
147  148   dragonair   Dragon     NaN     4.0    16.5          0    Dragon
148  149   dragonite   Dragon  Flying     2.2   210.0          0    Dragon
149  150      mewtwo  Psychic     NaN     2.0   122.0          1   Psychic

[150 rows x 8 columns]